<?php

class ModulosAdmin
{
    const DASHBOARD = 'DASHBOARD';
    const INSTITUTOS = 'INSTITUTOS';
    const SEDE = 'SEDE';
    const CATEGORY_LIST = 'CATEGORY_LIST';
    const CATEGORY_ADD = 'CATEGORY_ADD';
    const EVENTS = 'EVENTS';
    const EVENTS_LIST = 'EVENTS_LIST';
    const EVENTS_ADD = 'EVENTS_ADD';
    const PAGOS = 'PAGOS';
    const DEPOSITO_ALL = 'DEPOSITO_ALL';
    const PAGOS_COMPLETOS = 'PAGOS_COMPLETOS';
    const PAGOS_RECHAZADOS = 'PAGOS_RECHAZADOS';
    const PAGOS_INCOMPLETOS = 'PAGOS_INCOMPLETOS';
    const USERS = 'USERS';
    const INSCRIPCIONES = 'INSCRIPCIONES';
    const INSCRIPCIONES_ELIMINADAS = 'INSCRIPCIONES_ELIMINADAS';
    const MIS_RECAUDACIONES = 'MIS_RECAUDACIONES';
    const RECAUDACIONES = 'RECAUDACIONES';
    const RECAUDACIONES_ONLINE = 'RECAUDACIONES_ONLINE';
}

?>